vehicle:
  name: E1_KA04D5122_TANKER
  imei: '868683022806925'
  device_id: e1_ka04d5122_tanker
  vehicle_type: Tanker
  vehicle_number: KA04D5122
  zone_id: E
  max_speed_knots: 25.0
  depot_lat: 13.0209
  depot_lon: 77.6496
  odometer_offset_km: 29632
zone:
  name: E_Zone
  roads_geojson: data/zones/E_Zone/roads.geojson
  localities_file: data/zones/E_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 25
  sampling_jitter_seconds: 5
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
