vehicle:
  name: c1_ka02ac5939_jetting
  imei: '868683022806388'
  device_id: c1_ka02ac5939_jetting
  vehicle_type: jetting
  vehicle_number: KAO2AC5939
  zone_id: c1
  max_speed_knots: 25.0
  depot_lat: 12.958319
  depot_lon: 77.612422
zone:
  name: C_Zone
  roads_geojson: data/zones/C_Zone/roads.geojson
  localities_file: data/zones/C_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 25
  sampling_jitter_seconds: 5
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
