vehicle:
  name: E2_KA04D5289_tanker
  imei: '868683022792505'
  device_id: E2_KA04D5289_tanker
  vehicle_type: tanker
  vehicle_number: KA04d5289
  zone_id: E2
  max_speed_knots: 25.0
  depot_lat: 12.958319
  depot_lon: 77.612422
zone:
  name: E_Zone
  roads_geojson: data/zones/E_Zone/roads.geojson
  localities_file: data/zones/E_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 25
  sampling_jitter_seconds: 5
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
