vehicle:
  name: N2_KA04AB5791_Jetting
  imei: '864895033187814'
  device_id: N2_KA04AB5791_Jetting
  vehicle_type: Jetting
  vehicle_number: KA04AB5791
  zone_id: N2
  max_speed_knots: 25.0
  depot_lat: 12.958319
  depot_lon: 77.612422
zone:
  name: South_East_Bangalore
  roads_geojson: data/zones/South_East_Bangalore/roads.geojson
  localities_file: data/zones/South_East_Bangalore/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 25
  sampling_jitter_seconds: 5
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
