vehicle:
  name: NW1_KA04D3161_TANKER
  imei: '152748857818314'
  device_id: NW1_KA04D3161_TANKER
  vehicle_type: Tanker
  vehicle_number: KA04D3161
  zone_id: NW1
  max_speed_knots: 25.0
  depot_lat: 13.021008412499997
  depot_lon: 77.55491573750001
  odometer_offset_km: 0
  enabled: true
zone:
  name: NW_Zone
  roads_geojson: data/zones/NW_Zone/roads.geojson
  localities_file: data/zones/NW_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 900
  sampling_jitter_seconds: 0
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
simulation_window:
  start_date: '2022-05-01'
  end_date: '2024-04-30'
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
