vehicle:
  name: SE3_KA04AA7687_desilting
  imei: '864895033187368'
  device_id: SE3_KA04AA7687_desilting
  vehicle_type: desilting
  vehicle_number: KA04AA7687
  zone_id: SE3
  max_speed_knots: 25.0
  depot_lat: 12.958319
  depot_lon: 77.612422
zone:
  name: SE_Zone
  roads_geojson: data/zones/SE_Zone/roads.geojson
  localities_file: data/zones/SE_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 25
  sampling_jitter_seconds: 5
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
