vehicle:
  name: SE3_KA02AC5940_JETTING
  imei: '935100580253938'
  device_id: SE3_KA02AC5940_JETTING
  vehicle_type: Jetting
  vehicle_number: KA02AC5940
  zone_id: SE3
  max_speed_knots: 25.0
  depot_lat: 12.910219349999998
  depot_lon: 77.64025603750001
  odometer_offset_km: 0
  enabled: true
zone:
  name: SE_Zone
  roads_geojson: data/zones/SE_Zone/roads.geojson
  localities_file: data/zones/SE_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 900
  sampling_jitter_seconds: 0
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
simulation_window:
  start_date: '2021-05-01'
  end_date: '2022-04-30'
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
