vehicle:
  name: SW4_KA04AA9021_DESILTING
  imei: '434906898184025'
  device_id: SW4_KA04AA9021_DESILTING
  vehicle_type: Desilting
  vehicle_number: KA04AA9021
  zone_id: SW4
  max_speed_knots: 25.0
  depot_lat: 12.925012283333336
  depot_lon: 77.51864548333333
  odometer_offset_km: 0
  enabled: true
zone:
  name: SW_Zone
  roads_geojson: data/zones/SW_Zone/roads.geojson
  localities_file: data/zones/SW_Zone/localities.geojson
shift:
  timezone: Asia/Kolkata
  start_time: 09:00
  end_time: '19:00'
  sampling_interval_seconds: 900
  sampling_jitter_seconds: 0
calendar:
  working_days:
  - MON
  - TUE
  - WED
  - THU
  - FRI
  allow_saturdays: true
  saturday_probability_per_month: 2
  holidays_file: configs/calendars/india_2023_holidays.json
simulation_window:
  start_date: '2021-05-01'
  end_date: '2022-04-30'
routes:
  templates:
  - RT_DEFAULT
generation:
  random_seed: 12345
  output_root: data/output
  output_granularity: per_day
